SELECT C.CUSTOMER_NAME, T.PURCHASE_AMOUNT
FROM CUSTOMERS C 
JOIN CAMPAIGNS CA  
ON C.CUSTOMER_ID = CA.CUSTOMER_ID
JOIN TRANSACTIONS T 
ON C.CUSTOMER_ID = T.CUSTOMER_ID
WHERE T.TRANSACTION_DATE BETWEEN DATE_SUB(CA.PARTICIPATION_DATE, INTERVAL 6 MONTH) AND CA.PARTICIPATION_DATE
AND T.PURCHASE_AMOUNT >= 500;
