SELECT 
    CASE 
        WHEN C.AGE >= 20 AND C.AGE < 30 THEN '20대'
        WHEN C.AGE >= 30 AND C.AGE < 40 THEN '30대'
        WHEN C.AGE >= 40 AND C.AGE < 50 THEN '40대'

        ELSE '50대 이상'  
    END AS AGE_GROUP,
    SUM(T.PURCHASE_AMOUNT) AS TOTAL_PURCHASE 
FROM CUSTOMERS C 
JOIN TRANSACTIONS T 
ON C.CUSTOMER_ID = T.CUSTOMER_ID
GROUP BY AGE_GROUP;
