SELECT S.STAFF_NAME,COUNT(O.ANIMAL_ID)  AS ADOPTION_COUNT
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS O	ON A.ANIMAL_ID = O.ANIMAL_ID
JOIN STAFF S ON A.STAFF_ID = S.STAFF_ID
GROUP BY S.STAFF_NAME
ORDER BY ADOPTION_COUNT DESC, S.STAFF_NAME ASC
LIMIT 1;